# Generated by Django 6.0.1 on 2026-01-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatuser',
            name='avatar_bucket',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chatuser',
            name='avatar_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
