REGISTER_URL = "/api/auth/register/"
SEND_OTP_URL = "/api/auth/send-otp/"
VERIFY_OTP_URL = "/api/auth/verify-otp/"
REFRESH_URL = "/api/auth/refresh-token/"
LOGOUT_URL = "/api/auth/logout/"
ADD_CONTACTS_URL = "/api/auth/add-contacts/"
GET_CONTACTS_URL = "/api/auth/get-contacts/"

DUMMY_PASSWORD = "secret123"
DUMMY_EMAIL = "test@example.com"
DUMMY_USERNAME = "testuser"
DUMMY_NAME = "Test User"
