# Generated by Django 6.0 on 2026-01-03 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='hls_manifest_url',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='media_file',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='render_cache',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('file', 'File')], default='text', max_length=10),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('seen', 'Seen')], db_index=True, default='pending', max_length=10),
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket', models.CharField(max_length=255)),
                ('object_key', models.CharField(db_index=True, max_length=1024, unique=True)),
                ('kind', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('file', 'File')], max_length=10)),
                ('content_type', models.CharField(blank=True, max_length=255, null=True)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('processing_status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='queued', max_length=16)),
                ('processing_progress', models.FloatField(default=0.0)),
                ('variants', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_assets', to='chats.chatmessage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
