# Generated by Django 6.0 on 2026-01-06 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_remove_chatmessage_file_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='test_field',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
