# Generated by Django 6.0 on 2026-01-06 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_mediaasset_test_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediaasset',
            name='test_field',
        ),
    ]
