# Generated by Django 6.0 on 2026-01-15 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_remove_mediaasset_test_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaasset',
            name='processing_status',
            field=models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('done', 'Done'), ('partial', 'Partial'), ('failed', 'Failed')], db_index=True, default='queued', max_length=16),
        ),
    ]
