# Generated by Django 6.0.1 on 2026-02-06 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0007_remove_mediaasset_processing_progress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('seen', 'Seen'), ('failed', 'Failed')], db_index=True, default='pending', max_length=10),
        ),
    ]
