# Generated by Django 6.0.1 on 2026-02-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0008_alter_chatmessage_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaasset',
            name='object_key',
            field=models.CharField(db_index=True, max_length=1024),
        ),
    ]
